[[redirects]]
  from = "/api"
  to = "https://cs2102-petshop.herokuapp.com"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"